<a href="https://colab.research.google.com/github/Bhavyareddy-123/data-handling-and-visualization/blob/main/Copy_of_Numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


In [ ]:
import numpy as np
arr1=np.array([1,2,3])
print(arr1)
print(arr1[1])
arr1[1]=90
print(arr1)

[1 2 3]
2
[ 1 90  3]


In [ ]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2[1,1])
print(arr2[1,1])
print("\n")
print("order of matrix is", arr2.shape)

[[1 2 3]
 [4 5 6]]
5
5


order of matrix is (2, 3)


In [ ]:
import numpy as np
arr3 = np.arange(2,20,4)
print(arr3)

[ 2  6 10 14 18]


In [ ]:
arr5 = np.random.rand(10)
print(arr5)

[0.2004462  0.77973635 0.22037256 0.57651454 0.74108524 0.08084658
 0.20884447 0.79426841 0.32438205 0.88552943]


In [ ]:
arr7 = np.random.randint(5,10)
print(arr7)

6


In [ ]:
arr6 = np.array([4,5,6])
print(np.repeat(arr6,2))


[4 4 5 5 6 6]


In [ ]:
arr6=np.array([4,5,6])
print(np.tile(arr6,2))

[4 5 6 4 5 6]
